title: "Niku Singh"
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" 
url: "https://niku-singh.github.io/" 
twitter_username: Niku_Singh_
github_username:  NIKU-SINGH

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
